### ISSUE TITLE
Document Chip component

### ISSUE THREAD

**Issue by skclusive** [skclusive/Skclusive.Material.Docs#14]
Chip component is implemented. Need to add documentation similar to material-ui Chip https://material-ui.com/components/chips/#chip

Also need to use Chip component here in https://github.com/skclusive/Skclusive.Material.Docs/blob/master/Docs.App.View/Pages/Divider/Segments/MiddleDividers/MiddleDividersDemo.razor#L100

**Comment by henon** [comment]
ok, I'll do the documentation.

**Comment by skclusive** [comment]
@henon Chip component required rework in terms of parameter to match material-ui implementation. also the stylings were complex enough to force me implement the material-ui theming with color manipulation in C# (from their js implementation).

updated Chip document also.

https://github.com/skclusive/Skclusive.Material.Docs/tree/develop/Docs.App.View/Pages/Chip

**Comment by skclusive** [comment]
tweeted the chip video clip. https://twitter.com/skclusive/status/1298896106957365249

**Comment by henon** [comment]
Awesome. You took this much further than I could have!
