### ISSUE TITLE
Cannot open the solution in VS2019

### ISSUE THREAD

**Issue by win32nipuh** [skclusive/Skclusive.Material.Docs#3]
I have downloaded the Skclusive.Material.Docs solution to build, run and check some points: Theme switcher etc.
But I cannot open the solution in VS2019, it writes some of projects cannot be opened. Could you please check it?

**Comment by skclusive** [comment]
i do not have Visual Studio. might be project name changes are not updated. let me check.

**Comment by skclusive** [comment]
updated solution file with projects.

**Comment by win32nipuh** [comment]
The story continues :-)
Probably you are using Skclusive.Material.Layout.csproj which is located in the same solution. 
But by fact it is only in your environment. I have no it there, NuGet can be used.

```
1>E:\Projects\Blazor_1\Skclusive.Material.Docs-master\Docs.App.View\Docs.App.View.csproj : error NU1104: Unable to find project 'E:\Projects\Blazor_1\Skclusive.Material.Layout\src\Skclusive.Material.Layout.csproj'. Check that the project reference is valid and that the project file exists.
1>E:\Projects\Blazor_1\Skclusive.Material.Docs-master\Docs.App.View\Docs.App.View.csproj : error NU1104: Unable to find project 'E:\Projects\Blazor_1\Skclusive.Markdown.Component\src\Markdown.csproj'. Check that the project reference is valid and that the project file exists.

```

**Comment by win32nipuh** [comment]
What I have done finally: 
1. Removed the projects references from Docs.App.View
2. Added 2 NuGet Packages to the Docs.App.View:
Skclusive.Markdown.Component
Skclusive.Material.Layout
3. The project builds ok.

**Comment by skclusive** [comment]
yea. i was fixing bugs in layout post RC release. hence this issue occurred. will fix it. thanks for reporting.
