### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by Mhirji** [skclusive/Skclusive.Material.Docs#6]
On the documentation page for Buttons (and I believe this route is referenced in other places), the link with text "overrides documentation page" which points to https://skclusive.github.io/customization/components/ is broken.

**Comment by skclusive** [comment]
thanks for reporting. will check this out. feel free to contribute if your interested. otherwise will take it myself.

**Comment by skclusive** [comment]
removed the broken links to customization
