### ISSUE TITLE
Documentation - DrawerFrame

### ISSUE THREAD

**Issue by esso23** [skclusive/Skclusive.Material.Docs#8]
https://skclusive.github.io/Skclusive.Material.Docs/drawer
There is `DrawerFrame` component used in the example code (Responsive drawer) but that component does not exist anywhere in the solution.

Edit: Also there is `KeepMounted` parameter used on `Drawer` element which does not exist.

Edit2: `DrawerList` does not exist either.

**Comment by skclusive** [comment]
`<DrawerFrame />` is util component to host absolute/fixed positioned elements relative to a parent div. hence used in drawer to avoid getting rendered to body level. in material-ui demo, they have rendered the `<Drawer />` components inside `iframe` to avoid this.

you can find the utils components here:

https://github.com/skclusive/Skclusive.Material.Docs/blob/master/Docs.App.View/Pages/Drawer/Segments/DrawerFrame/DrawerFrame.razor

https://github.com/skclusive/Skclusive.Material.Docs/blob/master/Docs.App.View/Components/Frame.razor

And `<DrawerList />` is here

https://github.com/skclusive/Skclusive.Material.Docs/tree/master/Docs.App.View/Pages/Drawer/Segments/DrawerList

**Comment by skclusive** [comment]
closing this. let me know if you require more info.
